# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.215
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties

mod_id=alltheores
mod_name=AllTheOres
mod_license=All Rights Reserved
mod_version=3.1.7
mod_group_id=net.allthemods.alltheores
mod_authors=thevortex, whatthedrunk, Satherov
mod_description=Commonly found modded ores in one easy spot!.\nBrought to you by AllTheMods!

## Mod Dependencies

mekanism=mekanism-268560:6018306
jei_version=19.21.0.247
emi_version=1.1.19+1.21.1
ender_io_base=enderio-base:7.0.11-alpha
ender_io_machines=enderio-machines:7.0.11-alpha
immersiveengineering=immersive-engineering-231951:5828000
actually_additions=actually-additions-228404:6003504
adorned=adorned-1036809:5740650
forbidden_arcanus=forbidden-arcanus-309858:6875895
valhelsia_core=valhelsia-core-416935:5847440